theme: jekyll-theme-cayman
title: [3D Object Reconstruction with Soft Tactile Sensing]
description: [A website to document and display the results of Howard Zhang and David Deng's C106A Final Project on Soft Tactile Sensing]
