theme: jekyll-theme-cayman
title: [3D Object Reconstruction with Soft Tactile Sensing]
description: [A website by David Deng and Howard Zhang to document and display the results of our C106A Final Project on Soft Tactile Sensing]
